# -*- coding: utf-8 -*-
"""config.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yxu5MmYZTrWj5aq0HxdWgg2l1tJGJ_gn
"""

# config.py
"""
Configuration settings for the YouTube Channel Data Ingestion and LLM Analysis.

This script stores global variables such as API keys, search queries,
and predefined categories used across different modules of the application.
"""

# --- API Keys ---
# IMPORTANT: Replace with your actual YouTube Data API Key and Gemini API Key.
# It is highly recommended to use environment variables for production applications.
YOUTUBE_API_KEY = "*****"  # Replace with your YouTube Data API Key
GEMINI_API_KEY = "****"    # Replace with your Gemini API Key

# --- Gemini Model Configuration ---
GEMINI_MULTIMODAL_MODEL = 'gemini-2.0-flash'
GEMINI_TEXT_MODEL = 'gemini-2.0-flash'

# --- Search Queries (from your search query list.docx) ---
SEARCH_QUERIES = [
    'makeup artist', 'beauty blogger', 'makeup guru', 'beauty influencer', 'makeup channel',
    'american makeup artist', 'us beauty blogger', 'english speaking makeup artist',
    'north american makeup channel', 'natural makeup artist', 'glam makeup channel',
    'editorial makeup artist', 'bridal makeup channel', 'everyday makeup tutorial channel',
    'clean beauty influencer', 'affordable makeup channel', 'luxury beauty guru',
    'skincare and makeup channel', 'pro makeup techniques channel',
    'makeup tips and tricks channel', 'south asian makeup artist', 'indian makeup channel',
    'desilook makeup', 'east asian makeup tutorial channel', 'korean makeup artist us',
    'japanese makeup channel usa', 'black makeup artist', 'african american beauty guru',
    'dark skin makeup channel', 'latinx beauty blogger', 'hispanic makeup artist',
    'latina beauty channel', 'white makeup artist', 'caucasian beauty blogger',
    'american beauty channel'
]

# --- Predefined Categories (from your Table Schema.docx) ---
PREDEFINED_CATEGORIES = {
    "face_shape": ["round_face", "oval_face", "square_face", "heart_face", "long_face", "diamond_face"],
    "eye_shape": ["hooded_eyes", "almond_eyes", "round_eyes", "downturned_eyes", "monolid_eyes",
                  "up-turned_eyes", "deep_set_eyes", "close_set_eyes", "wide_set_eyes"],
    "skin_undertone": ["warm_undertone", "cool_undertone", "neutral_undertone"],
    "skin_type_concerns": ["oily_skin", "dry_skin", "combination_skin", "acne_prone_skin",
                           "sensitive_skin", "mature_skin"],
    "lip_shape": ["fuller_lips", "thin_lips", "heart_shaped_lips", "bow_shaped_lips"],
    "other_features": ["narrow_nose", "wide_nose", "high_cheeks", "low_cheeks"],
    "primary_makeup_style": ["natural", "everyday", "glam", "editorial", "bridal", "dramatic",
                             "minimalist", "soft_glam", "no_makeup_makeup"],
    "target_skill_level": ["beginner", "intermediate", "advanced", "pro_artist"],
    "demographic_focus": ["teen_focused", "adult_focused", "mature_age_focused", "dark_skin_tones",
                          "light_skin_tones", "male_makeup", "non_binary_makeup"],
    "llm_thumbnail_face_shape": ["Round", "Oval", "Square", "Heart", "Long", "Diamond", "unknown"],
    "llm_thumbnail_skin_color": ["fair", "light", "medium", "tan", "dark", "deep", "unknown"],
    "llm_thumbnail_eye_shape": ["Almond", "Round", "Hooded", "Monolid", "Downturned", "Up-turned",
                                 "Deep-set", "Close-set", "Wide-set", "unknown"],
    "llm_thumbnail_lip_shape": ["Fuller", "Thin", "Heart", "Bow", "unknown"],
    "llm_thumbnail_status": ["analyzed", "skipped_multiple_faces", "skipped_no_clear_face",
                             "error_processing_image", "error_llm_response", "pending", "unknown"]
}

# --- LLM Content Analysis Threshold ---
MIN_CONTENT_LENGTH_FOR_LLM = 100 # Minimum characters required for content analysis by LLM
